; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PCF Exporter Revit 2025"
#define MyAppVersion ".1"
#define MyAppPublisher "Farnsworth Group "

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{748DAE38-F0C5-4CB3-BF04-F6E392EC4F37}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName=C:\ProgramData\Autodesk\Revit\Addins\2025\PCF-Exporter
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=D:\_Projects\Programing\Github\acameronfw\Revit-PCF-Exporter\LICENSE.md
InfoBeforeFile=D:\_Projects\Programing\Github\acameronfw\Revit-PCF-Exporter\README.md
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=D:\_Projects\Programing\Github\PCF-Exporter Release\2025
OutputBaseFilename=PCF-Exporter
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "D:\_Projects\Programing\Github\acameronfw\Revit-PCF-Exporter\revit-pcf-exporter-2025\bin\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\_Projects\Programing\Github\acameronfw\Revit-PCF-Exporter\revit-pcf-exporter-2025\PCF_Exporter.addin"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2025"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

